### ISSUE TITLE
Generate output file for register doesn't currently work 

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan#31]
I believe the issue is something to do with Matplotlib, as the crash is occurring on this line
```ax.imshow(im)``` in analyse.py

**Comment by JoshuaSteer** [comment]
Weird, do you have the traceback for the error?

**Comment by jack-parsons** [comment]
>C:\Users\Jack\Anaconda3\envs\ampscan_env\lib\site-packages\vtk\util\numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
C:\Users\Jack\PycharmProjects\ampscan\AmpScan\core.py:249: RuntimeWarning: invalid value encountered in true_divide
  self.norm = np.divide(norms, mag[:,None])
Traceback (most recent call last):
  File "C:/Users/Jack/PycharmProjects/ampscan/GUIs/AmpScanGUI.py", line 305, in runRegistration
    reg.CMapOut(colors=self.CMapN2P)
  File "C:\Users\Jack\PycharmProjects\ampscan\AmpScan\analyse.py", line 382, in CMapOut
    ax.imshow(im)
  File "C:\Users\Jack\Anaconda3\envs\ampscan_env\lib\site-packages\matplotlib\__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Jack\Anaconda3\envs\ampscan_env\lib\site-packages\matplotlib\axes\_axes.py", line 5487, in imshow
    im.set_data(X)
  File "C:\Users\Jack\Anaconda3\envs\ampscan_env\lib\site-packages\matplotlib\image.py", line 649, in set_data
    raise TypeError("Image data cannot be converted to float")
TypeError: Image data cannot be converted to float

**Comment by JoshuaSteer** [comment]
That's a weird one, I'll have a look

**Comment by JoshuaSteer** [comment]
Does it work now?

**Comment by jack-parsons** [comment]
It still has the same error  :(

**Comment by JoshuaSteer** [comment]
@jack-parsons Have we fixed this yet?

**Comment by jack-parsons** [comment]
Not yet, still getting this error when you try to generate output for registration:
> C:\Users\Jack\Anaconda3\envs\ampscan_env\lib\site-packages\vtk\util\numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
C:\Users\Jack\PycharmProjects\ampscan\AmpScan\core.py:248: RuntimeWarning: invalid value encountered in true_divide
  self.norm = np.divide(norms, mag[:,None])
Traceback (most recent call last):
  File "C:/Users/Jack/PycharmProjects/ampscan/GUIs/AmpScanGUI.py", line 305, in runRegistration
    reg.CMapOut(colors=self.CMapN2P)
AttributeError: 'AmpObject' object has no attribute 'CMapOut'

**Comment by JoshuaSteer** [comment]
Right, I can fix that

**Comment by JoshuaSteer** [comment]
give it a try now?

**Comment by jack-parsons** [comment]
It works :)
![image](https://user-images.githubusercontent.com/7894397/63515691-525da580-c4e3-11e9-8610-a9af1a54a697.png)
